cmd_/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o := gcc -Wp,-MD,/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/.trk7.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.9.2/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m64 -mno-80387 -mno-fp-ret-in-387 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fvar-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(trk7)"  -D"KBUILD_MODNAME=KBUILD_STR(netcat)" -c -o /home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o /home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.c

source_/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o := /home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.c

deps_/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o := \
  /home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/../netcat.h \
  /home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/Isnt_It_Wonderful_FFX.h \

/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o: $(deps_/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o)

$(deps_/home/flavia/project-D8/Final_Project/musicPlayerKernelModule/tracks/trk7.o):
